import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Banner from "../Components/Header/Banner";
import Navbar from "../Components/Navigation/Navbar";
import Footer from "../Components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Plan B Burger Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth! scroll-auto">
      <body className={inter.className}>
        <Banner />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
